name = "todo-cloudflare"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "todo_db"
database_name = "todo-db"
database_id = "f725ffb3-e5b3-45a1-8f5d-02bccbec6ae9"

